---
- name: Create a GCP VM instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_id: mylab-465509   # Replace with your project ID
    region: us-central1  # e.g., us-central1
    zone: us-central1-a  # e.g., us-central1-a
    instance_name: my-awx-vm
    machine_type: e2-medium
    image: debian-cloud/debian-11
  tasks:
    - name: Create a new instance
      gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: /tmp/sa.json  # Replace with your key path
        image: "{{ image }}"
        state: present
        network_interfaces:
          - network: "projects/{{ project_id }}/global/networks/default"
      register: gcp_instance
    - debug:
        var: gcp_instance
