---
- name: Create a GCP VM instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    project_id: mylab-465509   # Replace with your GCP project ID
    machine_type: n1-standard-1  # Replace with your desired machine type
    zone: us-central1-a  # Replace with your desired zone
    image: debian-cloud/debian-10  # Replace with your desired image
    instance_name: my-awx-vm  # Replace with your desired instance name
    network_name: default # Replace with your desired network name
  tasks:
    - name: Create a GCP VM instance
      gcp_compute_instance:
        name: "{{ instance_name }}"
        machine_type: "{{ machine_type }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: /tmp/sa.json  # Replace with your service account file
        image: "{{ image }}"
        network: "{{ network_name }}"
        state: present
      register: gcp_vm

    - name: Print instance details
      debug:
        var: gcp_vm
