---
- name: Delete instances
  hosts: localhost
  gather_facts: yes
  vars:
      gcp_project: mylab-465509 
      gcp_cred_kind: serviceaccount
      #gcp_cred_file: /tmp/sa.json
      service_account_contents: "{{ lookup('credential', 'myGCP').service_account_contents }}"
      zone: "europe-west3-c"
      region: "europe-west3"
  tasks:
  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      #service_account_file: "{{ gcp_cred_file }}"
      service_account_contents: "{{ lookup('credential', 'myGCP').service_account_contents }}"
      state: present
    register: disk
  
  - name: create a network
    google.cloud.gcp_compute_network:
      name: network-instance
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      #service_account_file: "{{ gcp_cred_file }}"
      service_account_contents: "{{ lookup('credential', 'myGCP').service_account_contents }}"
      state: present
    register: network
  
  - name: create a address
    google.cloud.gcp_compute_address:
      name: address-instance
      region: us-central1
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      #service_account_file: "{{ gcp_cred_file }}"
      service_account_contents: "{{ lookup('credential', 'myGCP').service_account_contents }}"
      state: present
    register: address
  
  - name: create a instance
    google.cloud.gcp_compute_instance:
      name: test_object
      machine_type: n1-standard-1
      disks:
      - auto_delete: 'true'
        boot: 'true'
        source: "{{ disk }}"
      - auto_delete: 'true'
        interface: NVME
        type: SCRATCH
        initialize_params:
          disk_type: local-ssd
      metadata:
        startup-script-url: gs:://graphite-playground/bootstrap.sh
        cost-center: '12345'
      labels:
        environment: production
      network_interfaces:
      - network: "{{ network }}"
        access_configs:
        - name: External NAT
          nat_ip: "{{ address }}"
          type: ONE_TO_ONE_NAT
      zone: us-central1-a
      project: mylab-465509 
      auth_kind: serviceaccount
      #service_account_file: "/tmp/sa.json"
      service_account_contents: "{{ lookup('credential', 'myGCP').service_account_contents }}"
      state: present
