---
- name: start an instance with a public IP address
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Terminate every tag volatile
    amazon.aws.ec2_instance:
      state: absent
      region: eu-central-1
      filters:
        "tag:Type": "volatile"
