---

- name: delete instance in GCP

  hosts: localhost

  gather_facts: false

  vars:

    service_account_file: "sa.json"

    project: "mylab-465509"

    network_name: "test-ansible-network"

    subnet_name: "test-ansible-subnet"

    ip_name: "test-ansible-ip"

    disk_name: "test-ansible-disk"

    machine_name: "test-ansible"

    region: "europe-west3"

    zone: "europe-west3-a"

    source_image: "projects/debian-cloud/global/images/debian-12-bookworm-v20250709"

    subnet_cidr: "10.0.1.0/24"

    disk_size: 10

    machine_type: "e2-small"



  tasks:

    
  

        

    - name: delete an Instance 

      google.cloud.gcp_compute_instance:

        auth_kind: serviceaccount

        project: "{{ project }}"

        service_account_file: "{{ service_account_file }}"

        state: absent

        name: "{{ machine_name }}"

        machine_type: "{{ machine_type }}"

        zone: "{{ zone }}"

        
