---
- name: Monlithic FE
  hosts: 10.0.4.138
  become: yes

  tasks:
    - name: Installing Apache, MySQL and PHP
      yum:
        name:
          - httpd
          - mariadb-server
          - mariadb
          - php 
          - php-mysqlnd
        state: installed

    - name: Enabling and Starting the service httpd
      service:
        name: httpd
        enabled: yes
        state: started

    - name: Enabling and Starting the service MySQL
      service:
        name: mariadb
        enabled: yes
        state: started

    - name: firewalld rules
      ansible.posix.firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      with_items:
        - http
        - https
